### PR TITLE
Add conda environment support

### PR DESCRIPTION
**Pull request by ahmadia**

### CODE REVIEW

**Comment by ahmadia** [comment]
A couple of notes:
- This explicitly errors if both a requirements.txt and environment.yml are specified as dependencies to avoid surprises.  We could instead have the environment.yml "win", but it depends on use cases, which I'm not 100% clear on yet.
- ~~I'm using a bit of ugly sed Docker-build-time to get the name of the environment from the environment.yml.  If the contents of the file are available when app.py is being run, we could try slurping the file in (but then pyyaml becomes a dependency).~~

EDIT: Overriding the name of the environment in environment.yml to `binder` so that we can activate it without `sed` hackery.

**Comment by ahmadia** [comment]
Don't merge this, I've got a better solution.

**Comment by ahmadia** [comment]
Okay, fixed.

**Comment by andrewosh** [comment]
Cool, thanks @ahmadia! The changes look good, but unfortunately we don't have a great way to test these changes now (unless you have a local test machine, which as of now is tricky to set up!), so I'm just gonna pull them onto my test machine to make sure it all works. Going forward we should think about how we could get something like Travis to work for this. I'll let you know how that goes.

**Comment by ahmadia** [comment]
Sounds good.

**Comment by rgbkrk** [comment]
:boom:

**Pull request merged**
