### PR TITLE
Jupyter kernelspec

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by minrk** [comment]
These are not correct. The way to install the IPython kernelspec post-4.0 is `ipython kernel install`.

**Comment by basnijholt** [comment]
@minrk in building the Dockerimage this is printed:

```
Removing intermediate container 7cd608a4d3ef

Step 5 , RUN /bin/bash -c "source activate binder && ipython kernelspec install-self --user"

---> Running in fb3e105f7a93

discarding /home/main/anaconda2/bin from PATH

[91mprepending /home/main/anaconda2/envs/binder/bin to PATH

[91m[TerminalIPythonApp] WARNING | Subcommand `ipython kernelspec` is deprecated and will be removed in future versions. 

[91m[TerminalIPythonApp] WARNING | You likely want to use `jupyter kernelspec`... continue in 5 sec. Press Ctrl-C to quit now. 
```

**Comment by minrk** [comment]
`ipython kernelspec` did two things:
1. install Jupyter kernelspecs in general
2. install IPython's kernelspec for Jupyter via `install-self` (effectively calling `jupyter kernelspec install /path/to/ipython/kernelspec`)

(1) is now called `jupyter kernelspec`. `install-self` doesn't make sense for `jupyter kernelspec` because Jupyter doesn't provide any kernels itself. It only exists as a deprecated alias for the old IPython command. (2) continues to be an IPython command, now called `ipython kernel install`, which installs the IPython kernelspec.

I see now that the deprecations of `jupyter kernelspec install-self` are only in the code and not shown to the user. I'll fix that shortly.

**Comment by andrewosh** [comment]
@basnijholt thanks for the PR! As per @minrk's comment, I've updated the command to `ipython kernel install` as part of another update to the base image (https://github.com/binder-project/binder/commit/29c4e3dbda94e80b1b22c82997e554a25cd187ff), so I'll go ahead and close the issue.

Thanks again for the contribution!

**Pull request closed without merging**
